import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh-TW' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  'zh-TW': {
    // Navigation
    'nav.home': '首頁',
    'nav.products': '產品',
    'nav.about': '關於我們',
    'nav.contact': '聯絡我們',
    'nav.cart': '購物車',
    'nav.account': '我的帳戶',
    'nav.admin': '管理後台',
    'nav.login': '登入',
    'nav.logout': '登出',
    
    // Home Page
    'home.hero.title': 'ARVIX',
    'home.hero.kicker': '為日常儀式而設計',
    'home.hero.subtitle': '將日常時刻轉化為平靜、觸感體驗的極簡工具——專為專注、攜帶和家居而打造。',
    'home.hero.cta': '選購生產力工具',
    'home.hero.ctaSecondary': '探索攜帶系列',
    'home.hero.shipping': '國內配送',
    'home.hero.shippingDays': '2-3 天',
    'home.hero.returns': '輕鬆退貨',
    'home.hero.returnsDays': '30 天',
    'home.hero.secure': '安全',
    'home.hero.secureText': '結帳與隱私',
    'home.featured.title': '精選商品',
    'home.featured.subtitle': '為您的日常精選的必需品',
    'home.collections.title': '探索系列',
    'home.collections.subtitle': '為您日常生活各方面精心策劃的工具',
    'home.collections.viewAll': '選購產品',
    'home.categories.title': '所有類別',
    'home.categories.subtitle': '找到您需要的一切',
    'home.categories.shopNow': '立即選購 →',
    'home.brands.featured': '精選於',
    'home.value.title': '注重細節',
    'home.value.subtitle': '優質材料、安靜設計和周到實用——沒有噪音。',
    'home.value.material': '材料優先',
    'home.value.materialDesc': '乾淨的表面處理、耐用的構造和您每天都會注意到的觸感。',
    'home.value.carry': '為攜帶而設計',
    'home.value.carryDesc': '纖薄的外形和有目的的形式因素——易於攜帶，易於保存。',
    'home.value.lasting': '經久耐用',
    'home.value.lastingDesc': '永恆的美學與長期可用性。更少雜亂，更多平靜。',
    'home.testimonials.title': '客戶評價',
    'home.testimonials.subtitle': '一些重視平靜、功能和工藝的人的評論。',
    'home.testimonials.quote1': '表面處理令人難以置信。這是您想放在桌上的那種工具。',
    'home.testimonials.quote2': '極簡但不無聊。一切都經過深思熟慮。',
    'home.testimonials.quote3': '完美融入我的日常攜帶。質量超出預期。',
    
    // Product
    'product.addToCart': '加入購物車',
    'product.outOfStock': '缺貨中',
    'product.comingSoon': '即將推出',
    'product.price': '價格',
    'product.description': '描述',
    'product.quantity': '數量',
    'product.viewDetails': '查看詳情',
    'product.view': '查看',
    'product.featured': '精選',
    'product.addedToCart': '已加入購物車',
    'product.continue': '繼續',
    'product.viewCart': '查看購物車',
    'product.notFound': '找不到產品',
    'product.notFoundDesc': '您要找的產品不存在。',
    'product.backToProducts': '返回產品',
    'product.youMightLike': '您可能也喜歡',
    'product.noRelated': '暫無相關產品。',
    'product.specs': '產品規格',
    'product.features': '主要特點',
    'product.feature.premium': '優質材料',
    'product.feature.minimal': '極簡設計',
    'product.feature.durable': '耐用結構',
    'product.feature.easy': '易於使用',
    'product.returns': '30天退貨',
    'product.shipping': '2-3天國內配送',
    
    // Cart
    'cart.title': '購物車',
    'cart.empty': '購物車是空的',
    'cart.continueShopping': '繼續購物',
    'cart.checkout': '結帳',
    'cart.subtotal': '小計',
    'cart.total': '總計',
    'cart.remove': '移除',
    'cart.items': '件商品',
    'cart.estimatedTax': '預估稅金',
    'cart.freeShipping': '免運費',
    'cart.freeShippingHint': '再加',
    'cart.freeShippingMore': '即可享免運費。',
    'cart.recommendations': '您可能也喜歡',
    'cart.checkoutNote': '結帳時計算稅金和運費。您的支付詳情已加密。',
    
    // Checkout
    'checkout.title': '結帳',
    'checkout.orderSummary': '訂單摘要',
    'checkout.paymentMethod': '支付方式',
    'checkout.selectPayment': '選擇支付方式',
    'checkout.proceedToPayment': '前往支付',
    'checkout.processing': '處理中...',
    'checkout.backToCart': '返回購物車',
    'checkout.shipping': '運費',
    'checkout.toBeCalculated': '待計算',
    'checkout.amountDetails': '金額明細',
    'checkout.confirmationNote': '支付完成後，您將收到訂單確認郵件',
    
    // Payment
    'payment.creditCard': '信用卡',
    'payment.atm': 'ATM 轉賬',
    'payment.cvs': '超商代碼',
    'payment.barcode': '超商條碼',
    'payment.newebpay': '藍新金流 (NewebPay)',
    'payment.ecpay': '綠界科技 (ECPay)',
    'payment.creditCard.desc': '支持 Visa、Mastercard、JCB',
    'payment.atm.desc': '虛擬帳號轉賬，3天內完成',
    'payment.cvs.desc': '7-11、全家、萊爾富',
    'payment.barcode.desc': '超商掃碼支付',
    
    // Account
    'account.title': '我的帳戶',
    'account.orders': '我的訂單',
    'account.profile': '個人資料',
    'account.addresses': '收貨地址',
    'account.orderHistory': '訂單記錄',
    'account.orderNumber': '訂單編號',
    'account.date': '日期',
    'account.status': '狀態',
    'account.amount': '金額',
    'account.viewDetails': '查看詳情',
    
    // Order Status
    'order.status.pending': '待處理',
    'order.status.paid': '已付款',
    'order.status.processing': '處理中',
    'order.status.shipped': '已出貨',
    'order.status.delivered': '已送達',
    'order.status.cancelled': '已取消',
    'order.status.refunded': '已退款',
    
    // Auth
    'auth.login': '登入',
    'auth.register': '註冊',
    'auth.email': '電子郵件',
    'auth.password': '密碼',
    'auth.confirmPassword': '確認密碼',
    'auth.forgotPassword': '忘記密碼？',
    'auth.noAccount': '還沒有帳戶？',
    'auth.hasAccount': '已有帳戶？',
    'auth.signUp': '註冊',
    'auth.signIn': '登入',
    
    // Common
    'common.loading': '載入中...',
    'common.error': '錯誤',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.confirm': '確認',
    'common.save': '儲存',
    'common.edit': '編輯',
    'common.delete': '刪除',
    'common.search': '搜尋',
    'common.filter': '篩選',
    'common.sort': '排序',
    'common.viewMore': '查看更多',
    'common.backToTop': '回到頂部',
    
    // Footer
    'footer.company': '公司資訊',
    'footer.about': '關於我們',
    'footer.careers': '人才招募',
    'footer.press': '媒體中心',
    'footer.support': '客戶支持',
    'footer.help': '幫助中心',
    'footer.shipping': '配送資訊',
    'footer.returns': '退換貨政策',
    'footer.contact': '聯絡我們',
    'footer.social': '關注我們',
    'footer.newsletter': '訂閱電子報',
    'footer.newsletterDesc': '訂閱以獲取最新優惠和產品資訊',
    'footer.subscribe': '訂閱',
    'footer.copyright': '© 2024 時光科技. 版權所有.',
    
    // Login/Register
    'login.title': '登入',
    'login.subtitle': '登入您的帳戶',
    'login.submit': '登入',
    'login.noAccount': '還沒有帳戶？',
    'login.createAccount': '建立帳戶',
    'register.title': '註冊',
    'register.subtitle': '建立新帳戶',
    'register.submit': '註冊',
    'register.hasAccount': '已有帳戶？',
    'register.signIn': '登入',
    
    // Account Page
    'account.welcome': '歡迎回來',
    'account.recentOrders': '最近訂單',
    'account.noOrders': '您還沒有任何訂單',
    'account.startShopping': '開始購物',
    'account.viewAll': '查看全部',
    'account.orderDetails': '訂單詳情',
    'account.payNow': '立即支付',
    
    // Product Collection
    'collection.home': '首頁',
    'collection.allProducts': '所有產品',
    'collection.products': '產品',
    'collection.product': '產品',
    'collection.results': '結果',
    'collection.searchPlaceholder': '搜尋產品...',
    'collection.sortBy': '排序：',
    'collection.featured': '精選',
    'collection.priceLowHigh': '價格：低到高',
    'collection.priceHighLow': '價格：高到低',
    'collection.nameAZ': '名稱：A 到 Z',
    'collection.noProducts': '找不到產品',
    'collection.noProductsDesc': '稍後查看此類別的新品。',
    'collection.noSearchResults': '沒有產品匹配',
    'collection.tryDifferent': '嘗試不同的搜尋詞。',
    'collection.shopOther': '選購其他類別',
    'collection.searchTips': '搜尋提示：',
    'collection.checkSpelling': '檢查您的拼寫',
    'collection.tryGeneral': '嘗試更通用的關鍵字',
    'collection.browseCategories': '按類別瀏覽',
    
    // Search
    'search.placeholder': '搜尋產品...',
    'search.searching': '搜尋中...',
    'search.popular': '熱門搜尋',
    'search.resultsFound': '找到結果',
    'search.noResults': '找不到結果',
    'search.tryDifferent': '嘗試使用不同的關鍵字搜尋',
    
    // About & Contact
    'about.title': '關於我們',
    'about.subtitle': '通過極簡創新設計增強日常生活的工具',
    'about.story': '我們的故事',
    'about.storyText1': 'ARVIX 始於一個簡單的問題：我們如何讓日常工具變得更好？從這個問題中產生了對極簡設計、功能創新和卓越品質的承諾。',
    'about.storyText2': '我們相信最好的工具是那些融入您日常生活的工具，無縫工作直到您忘記它們的存在。這就是為什麼每個 ARVIX 產品都是有目的、精確和對細節的不懈關注而設計的。',
    'about.philosophy': '我們的理念',
    'about.philosophy.purpose': '目的驅動設計',
    'about.philosophy.purposeDesc': '每個產品都從明確的目的開始，解決真實問題',
    'about.philosophy.minimal': '極簡效率',
    'about.philosophy.minimalDesc': '更少複雜性，每次互動更多功能',
    'about.philosophy.craft': '工藝',
    'about.philosophy.craftDesc': '優質材料和精密製造',
    'about.philosophy.innovation': '創新',
    'about.philosophy.innovationDesc': '推動日常工具的界限',
    'about.journey': '我們的旅程',
    'about.journey.2020': '成立',
    'about.journey.2020desc': 'ARVIX 誕生於對極簡設計的熱情',
    'about.journey.2021': '首次產品發布',
    'about.journey.2021desc': '推出我們的旗艦生產力工具',
    'about.journey.2022': '全球擴張',
    'about.journey.2022desc': '覆蓋 25+ 個國家的客戶',
    'about.journey.2024': '創新持續',
    'about.journey.2024desc': '50+ 產品並持續增長',
    'about.commitment': '我們的承諾',
    'about.commitment.quality': '品質保證',
    'about.commitment.qualityDesc': '每個產品都經過嚴格測試以確保可靠性和耐用性',
    'about.commitment.sustainable': '可持續實踐',
    'about.commitment.sustainableDesc': '環保材料和負責任的製造流程',
    'about.commitment.customer': '客戶至上',
    'about.commitment.customerDesc': '您的滿意度推動我們的創新和改進',
    'about.behind': '幕後',
    'about.getInTouch': '聯繫我們',
    'about.support': '客戶支持',
    'about.supportEmail': 'support@xyvn.com',
    'about.supportHours': '週一至週五：上午 9:00 - 下午 6:00 (GMT+8)',
    'about.media': '媒體查詢',
    'about.mediaEmail': 'media@xyvn.com',
    'about.partnerships': '商業合作',
    'about.partnershipsEmail': 'partnerships@xyvn.com',
    'about.stats.products': '產品',
    'about.stats.customers': '滿意客戶',
    'about.stats.countries': '國家',
    'about.stats.satisfaction': '滿意度',
    'contact.title': '聯絡我們',
    'contact.subtitle': '我們很樂意聽取您的意見。給我們發送消息，我們會盡快回复。',
    'contact.name': '姓名',
    'contact.message': '訊息',
    'contact.send': '發送訊息',
    'contact.success': '訊息已發送！',
    'contact.subject': '主題',
    'contact.subjectPlaceholder': '我們能如何幫助您？',
    'contact.messagePlaceholder': '告訴我們更多關於您的查詢...',
    'contact.info': '聯絡資訊',
    'contact.emailSupport': '電子郵件支持',
    'contact.emailSupportDesc': '我們在工作日 24 小時內回复',
    'contact.socialMedia': '社交媒體',
    'contact.office': '辦公地點',
    'contact.officeLocation': '台北，台灣',
    'contact.officeHours': '週一至週五：上午 9:00 - 下午 6:00',
    'contact.faq': '常見問題',
    'contact.faqDesc': '快速找到常見問題的答案',
    'contact.viewFaq': '查看常見問題',
    'contact.expect': '期待什麼',
    'contact.responseTime': '回應時間',
    'contact.responseTimeDesc': '商業查詢 24 小時內',
    'contact.supportHours': '支持時間',
    'contact.supportHoursDesc': '週一至週五，上午 9:00 - 下午 6:00 (GMT+8)',
    'contact.languages': '語言',
    'contact.languagesDesc': '英語、中文（繁體和簡體）',
    'contact.faqIntro': '關於結帳、配送和退貨的快速答案。',
  },
  'en': {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.account': 'Account',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Home Page
    'home.hero.title': 'ARVIX',
    'home.hero.kicker': 'Designed for daily rituals',
    'home.hero.subtitle': 'Minimal tools that turn routine moments into calm, tactile experiences—built for focus, carry, and home.',
    'home.hero.cta': 'Shop Productivity',
    'home.hero.ctaSecondary': 'Explore Carry',
    'home.hero.shipping': 'Domestic shipping',
    'home.hero.shippingDays': '2–3 days',
    'home.hero.returns': 'Easy returns',
    'home.hero.returnsDays': '30 days',
    'home.hero.secure': 'Secure',
    'home.hero.secureText': 'Checkout & privacy',
    'home.featured.title': 'Featured Products',
    'home.featured.subtitle': 'Handpicked essentials for your everyday',
    'home.collections.title': 'Explore Collections',
    'home.collections.subtitle': 'Curated tools for every aspect of your daily life',
    'home.collections.viewAll': 'Shop Products',
    'home.categories.title': 'All Categories',
    'home.categories.subtitle': 'Find exactly what you need',
    'home.categories.shopNow': 'Shop Now →',
    'home.brands.featured': 'Featured in',
    'home.value.title': 'Built for the details',
    'home.value.subtitle': 'Premium materials, quiet design, and thoughtful utility—without the noise.',
    'home.value.material': 'Material-first',
    'home.value.materialDesc': 'Clean finishes, durable builds, and a tactile feel you\'ll notice every day.',
    'home.value.carry': 'Made to carry',
    'home.value.carryDesc': 'Slim profiles and purposeful form factors—easy to take, easy to keep.',
    'home.value.lasting': 'Designed to last',
    'home.value.lastingDesc': 'Timeless aesthetics with long-term usability. Less clutter, more calm.',
    'home.testimonials.title': 'What customers say',
    'home.testimonials.subtitle': 'A few notes from people who value calm, function, and craft.',
    'home.testimonials.quote1': 'The finish is unreal. It\'s the kind of tool you want to keep on your desk.',
    'home.testimonials.quote2': 'Minimal but not boring. Everything feels considered.',
    'home.testimonials.quote3': 'Fits perfectly in my everyday carry. Quality is better than expected.',
    
    // Product
    'product.addToCart': 'Add to Cart',
    'product.outOfStock': 'Out of Stock',
    'product.comingSoon': 'Coming Soon',
    'product.price': 'Price',
    'product.description': 'Description',
    'product.quantity': 'Quantity',
    'product.viewDetails': 'View Details',
    'product.view': 'View',
    'product.featured': 'Featured',
    'product.addedToCart': 'Added to cart',
    'product.continue': 'Continue',
    'product.viewCart': 'View cart',
    'product.notFound': 'Product Not Found',
    'product.notFoundDesc': 'The product you\'re looking for doesn\'t exist.',
    'product.backToProducts': 'Back to Products',
    'product.youMightLike': 'You might also like',
    'product.noRelated': 'No related products yet.',
    'product.specs': 'Product Specs',
    'product.features': 'Key Features',
    'product.feature.premium': 'Premium Materials',
    'product.feature.minimal': 'Minimalist Design',
    'product.feature.durable': 'Durable Construction',
    'product.feature.easy': 'Easy to Use',
    'product.returns': '30-day returns',
    'product.shipping': '2–3 day domestic shipping',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.continueShopping': 'Continue Shopping',
    'cart.checkout': 'Checkout',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.remove': 'Remove',
    'cart.items': 'items',
    'cart.estimatedTax': 'Estimated tax',
    'cart.freeShipping': 'Free',
    'cart.freeShippingHint': 'Add',
    'cart.freeShippingMore': 'more for free shipping.',
    'cart.recommendations': 'You might also like',
    'cart.checkoutNote': 'Taxes and shipping calculated at checkout. Your payment details are encrypted.',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.orderSummary': 'Order Summary',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.selectPayment': 'Select Payment Method',
    'checkout.proceedToPayment': 'Proceed to Payment',
    'checkout.processing': 'Processing...',
    'checkout.backToCart': 'Back to Cart',
    'checkout.shipping': 'Shipping',
    'checkout.toBeCalculated': 'To be calculated',
    'checkout.amountDetails': 'Amount Details',
    'checkout.confirmationNote': 'You will receive an order confirmation email after payment',
    
    // Payment
    'payment.creditCard': 'Credit Card',
    'payment.atm': 'ATM Transfer',
    'payment.cvs': 'CVS Code',
    'payment.barcode': 'CVS Barcode',
    'payment.newebpay': 'NewebPay',
    'payment.ecpay': 'ECPay',
    'payment.creditCard.desc': 'Visa, Mastercard, JCB',
    'payment.atm.desc': 'Virtual account, complete within 3 days',
    'payment.cvs.desc': '7-11, FamilyMart, Hi-Life',
    'payment.barcode.desc': 'Scan at convenience store',
    
    // Account
    'account.title': 'My Account',
    'account.orders': 'My Orders',
    'account.profile': 'Profile',
    'account.addresses': 'Addresses',
    'account.orderHistory': 'Order History',
    'account.orderNumber': 'Order Number',
    'account.date': 'Date',
    'account.status': 'Status',
    'account.amount': 'Amount',
    'account.viewDetails': 'View Details',
    
    // Order Status
    'order.status.pending': 'Pending',
    'order.status.paid': 'Paid',
    'order.status.processing': 'Processing',
    'order.status.shipped': 'Shipped',
    'order.status.delivered': 'Delivered',
    'order.status.cancelled': 'Cancelled',
    'order.status.refunded': 'Refunded',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUp': 'Sign Up',
    'auth.signIn': 'Sign In',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.viewMore': 'View More',
    'common.backToTop': 'Back to Top',
    
    // Footer
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'footer.shipping': 'Shipping Info',
    'footer.returns': 'Returns Policy',
    'footer.contact': 'Contact Us',
    'footer.social': 'Follow Us',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDesc': 'Subscribe for latest offers and updates',
    'footer.subscribe': 'Subscribe',
    'footer.copyright': '© 2024 Seedlight Tech. All rights reserved.',
    
    // Login/Register
    'login.title': 'Login',
    'login.subtitle': 'Sign in to your account',
    'login.submit': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.createAccount': 'Create Account',
    'register.title': 'Register',
    'register.subtitle': 'Create a new account',
    'register.submit': 'Register',
    'register.hasAccount': 'Already have an account?',
    'register.signIn': 'Sign In',
    
    // Account Page
    'account.welcome': 'Welcome back',
    'account.recentOrders': 'Recent Orders',
    'account.noOrders': 'You have no orders yet',
    'account.startShopping': 'Start Shopping',
    'account.viewAll': 'View All',
    'account.orderDetails': 'Order Details',
    'account.payNow': 'Pay Now',
    
    // Product Pages
    'product.relatedProducts': 'Related Products',
    'product.specifications': 'Specifications',
    'product.reviews': 'Reviews',
    'product.inStock': 'In Stock',
    'product.limitedStock': 'Limited Stock',
    
    // Product Collection
    'collection.home': 'Home',
    'collection.allProducts': 'All Products',
    'collection.products': 'products',
    'collection.product': 'product',
    'collection.results': 'results',
    'collection.searchPlaceholder': 'Search products...',
    'collection.sortBy': 'Sort by:',
    'collection.featured': 'Featured',
    'collection.priceLowHigh': 'Price: Low to High',
    'collection.priceHighLow': 'Price: High to Low',
    'collection.nameAZ': 'Name: A to Z',
    'collection.noProducts': 'No products found',
    'collection.noProductsDesc': 'Check back later for new arrivals in this category.',
    'collection.noSearchResults': 'No products match',
    'collection.tryDifferent': 'Try a different search term.',
    'collection.shopOther': 'Shop Other Categories',
    'collection.searchTips': 'Search tips:',
    'collection.checkSpelling': 'Check your spelling',
    'collection.tryGeneral': 'Try more general keywords',
    'collection.browseCategories': 'Browse by categories',
    
    // Search
    'search.placeholder': 'Search products...',
    'search.searching': 'Searching...',
    'search.popular': 'Popular Searches',
    'search.resultsFound': 'results found',
    'search.noResults': 'No results found',
    'search.tryDifferent': 'Try searching with different keywords',
    
    // About & Contact
    'about.title': 'About Us',
    'about.subtitle': 'Designing tools that enhance everyday life through minimalist innovation',
    'about.story': 'Our Story',
    'about.storyText1': 'ARVIX began with a simple question: How can we make everyday tools better? From this question grew a commitment to minimalist design, functional innovation, and exceptional quality.',
    'about.storyText2': 'We believe that the best tools are those that disappear into your daily routine, working seamlessly until you forget they\'re even there. That\'s why every ARVIX product is designed with purpose, precision, and an unwavering attention to detail.',
    'about.philosophy': 'Our Philosophy',
    'about.philosophy.purpose': 'Purpose-Driven Design',
    'about.philosophy.purposeDesc': 'Every product starts with a clear purpose and solves a real problem',
    'about.philosophy.minimal': 'Minimalist Efficiency',
    'about.philosophy.minimalDesc': 'Less complexity, more functionality in every interaction',
    'about.philosophy.craft': 'Craftsmanship',
    'about.philosophy.craftDesc': 'Premium materials and precision manufacturing',
    'about.philosophy.innovation': 'Innovation',
    'about.philosophy.innovationDesc': 'Pushing boundaries of what everyday tools can be',
    'about.journey': 'Our Journey',
    'about.journey.2020': 'Founded',
    'about.journey.2020desc': 'ARVIX was born from a passion for minimalist design',
    'about.journey.2021': 'First Product Launch',
    'about.journey.2021desc': 'Introduced our flagship productivity tools',
    'about.journey.2022': 'Global Expansion',
    'about.journey.2022desc': 'Reached customers in 25+ countries',
    'about.journey.2024': 'Innovation Continues',
    'about.journey.2024desc': '50+ products and growing',
    'about.commitment': 'Our Commitment',
    'about.commitment.quality': 'Quality Assurance',
    'about.commitment.qualityDesc': 'Every product undergoes rigorous testing to ensure reliability and durability',
    'about.commitment.sustainable': 'Sustainable Practices',
    'about.commitment.sustainableDesc': 'Environmentally conscious materials and responsible manufacturing processes',
    'about.commitment.customer': 'Customer Focus',
    'about.commitment.customerDesc': 'Your satisfaction drives our innovation and improvement',
    'about.behind': 'Behind the Scenes',
    'about.getInTouch': 'Get in Touch',
    'about.support': 'Customer Support',
    'about.supportEmail': 'support@xyvn.com',
    'about.supportHours': 'Mon-Fri: 9:00 AM - 6:00 PM (GMT+8)',
    'about.media': 'Media Inquiries',
    'about.mediaEmail': 'media@xyvn.com',
    'about.partnerships': 'Business Partnerships',
    'about.partnershipsEmail': 'partnerships@xyvn.com',
    'about.stats.products': 'Products',
    'about.stats.customers': 'Happy Customers',
    'about.stats.countries': 'Countries',
    'about.stats.satisfaction': 'Satisfaction',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    'contact.name': 'Name',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.success': 'Message sent!',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'How can we help?',
    'contact.messagePlaceholder': 'Tell us more about your inquiry...',
    'contact.info': 'Contact Information',
    'contact.emailSupport': 'Email Support',
    'contact.emailSupportDesc': 'We respond within 24 hours on weekdays',
    'contact.socialMedia': 'Social Media',
    'contact.office': 'Office Location',
    'contact.officeLocation': 'Taipei, Taiwan',
    'contact.officeHours': 'Mon-Fri: 9:00 AM - 6:00 PM',
    'contact.faq': 'FAQ',
    'contact.faqDesc': 'Find quick answers to common questions',
    'contact.viewFaq': 'View FAQ',
    'contact.expect': 'What to Expect',
    'contact.responseTime': 'Response Time',
    'contact.responseTimeDesc': 'Within 24 hours for business inquiries',
    'contact.supportHours': 'Support Hours',
    'contact.supportHoursDesc': 'Monday - Friday, 9:00 AM - 6:00 PM (GMT+8)',
    'contact.languages': 'Languages',
    'contact.languagesDesc': 'English, Chinese (Traditional & Simplified)',
    'contact.faqIntro': 'Quick answers about checkout, shipping, and returns.',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'zh-TW') ? saved : 'zh-TW';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
